### ISSUE TITLE
Function keys not enabled

### ISSUE THREAD

**Issue by maciej-skurznica** [crobin93/youtube-anywhere-remote#3]
Hi bro. Would be nice if the shortcuts can be assigned to function keys on mac.

**Comment by chris-mcdonald-dev** [comment]
I wish that were possible, but Chromium's browser API only allows certain keys to be mapped. The function keys aren't included in that list.
[Chromium API Docs - Supported Keys](https://developer.chrome.com/docs/extensions/reference/commands/#supported-keys)
